apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: MY_SECRET_NAME
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gsm
    kind: SecretStore
  target:
    name: MY_SECRET_NAME
