apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: MY_APP
  annotations:
    description: Binds cluster-admin to every member and relevant SAs within a product. Allows all subjects to have full rights within their namespace. Usually reserved for dev/sandbox
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: MY_EMAIL
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin