apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kartverket/argokit.git/manifests/secretstore-gsm.yaml?ref=v0.1.0
- https://github.com/kartverket/argokit.git/manifests/externalsecret-gsm.yaml?ref=v0.1.0

patches:
- path: patches/secretstore.patch.yaml
  target:
    kind: SecretStore
- path: patches/externalsecret.patch.yaml
  target:
    kind: ExternalSecret
